@apiURL = https://viritual-board-login.onrender.com/users

GET {{apiURL}}

###
POST {{apiURL}}
Content-Type: application/json

{
    "username": "Stubb",
    "email": "stubb@test.com",
    "password": "stubb"

}

###
POST {{apiURL}}/login
Content-Type: application/json

{
    "email": "sauli@test.com",
    "password": "sauli"
}