version: "3.9"

services:
  node-app:
    build:
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - MODE=development   

volumes:
  node_modules:
